### ISSUE TITLE
Host unreachable in latest version of mosquitto

### ISSUE THREAD

**Issue by spagnoloG** [vvatelot/mosquitto-docker-compose#1]
https://github.com/vvatelot/mosquitto-docker-compose/blob/21626037aa1a15839740f7e28ed914bbd8202240/config/mosquitto.conf#L3

Add field in configuration file: `listener 1883`

source: https://github.com/eclipse/mosquitto/issues/2040#issuecomment-767944740

**Comment by nixilb** [comment]
ALWAYS set the version of the image (and NEVER use LATEST).
When Mosquitto goes 2.0, All tutorials that didn't follow this rule stopped working.

**Comment by vvatelot** [comment]
Hello @spagnoloG @nixilb @martinbra, so so sorry! I was not aware of this issue since I did not received any notification from github (seems that I disable by default notification on my own repo...)

You are completely right, and here is what I propose:
- We freeze the current docker version to 1, and I create a release 1.0.0 on the github repo with the current configuration working
- We create a new release 2.0.0 with the docker version 2 and make evolve the configuration

Does this seem great to you?

**Comment by martinbra** [comment]
Thanks @vvatelot, seems good to me!

**Comment by vvatelot** [comment]
Thank you very much @martinbra for the help on this issue!
I created the [release v2.0.0](https://github.com/vvatelot/mosquitto-docker-compose/releases/tag/v2.0.0) which is now the default version

**Comment by martinbra** [comment]
Oh, sorry @vvatelot , I commited yesterday, but I was in a rush and didn't had the time to comment back here.

**Comment by vvatelot** [comment]
Don't worry ! That's ok 🙂
